version: '3.8'

services:
  nutrition-frontend:
    env_file:
      - Frontend/.env
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nutrition-backend
    networks:
      - nutrition-network

  nutrition-backend:
    env_file:
      - Backend/.env
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - nutrition-network

  mongodb:
    image: mongo:latest
    container_name: nutrition_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    command: mongod --auth
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - nutrition-network

volumes:
  mongodb_data: 

networks:
  nutrition-network:
    driver: bridge 